config/routes.rb
Rails.application.routes.draw do
  resources :runs, only: [:new, :create, :show, :edit, :update]
  post 'runs/jump' => 'runs#jump'
  root 'welcome#index'
end

app/models/jump.rb
class Jump < ActiveRecord::Base
  belongs_to :run
  belongs_to :obstacle

  def correct_option
    obstacle.correct_option
  end
end

app/models/obstacle.rb
require 'non_repetitive_random_generator'

class Obstacle < ActiveRecord::Base
  has_many :jumps

  validate :options_uniqueness, :options_include_correct

  def self.next
    @random1 ||= NonRepetitiveRandomNumberGenerator.new
    @random2 ||= NonRepetitiveRandomNumberGenerator.new
    number1 = @random1.next(10)
    number2 = @random2.next(10)
    sum = number1 + number2
    options = [sum]
    3.times do |n|
      option = sum + (n+1) * (flip_coin ? 1 : -1)
      options.send(flip_coin ? :push  : :unshift, option)
    end
    new(question: "#{number1} + #{number2}",
        options_string: options.join('|'),
          correct_option: sum.to_s)
  end

  def options
    @options ||= options_string.split('|')
  end

  private

  def self.flip_coin
    Random.rand < 0.5
  end

  def options_uniqueness
    options.group_by{|e| e}.select{|k, v| v.size>1}.map{|k, v| k}.each do |opt|
      errors.add(:options_string, "Duplicate option #{opt}")
    end
  end

  def options_include_correct
    unless options.include? correct_option
      errors.add(:options_string, 'must include the correct option')
    end
  end
end

app/models/run.rb
class Run < ActiveRecord::Base
  has_many :jumps

  def current_jump
    jumps.empty? ? next_jump : jumps.last
  end

  def next_jump
    jumps.create!(obstacle: Obstacle.next)
    jumps.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run_and_jump, only: [:show, :edit, :update, :jump]

  # GET /runs/1
  def show
    set_obstacle
  end

  # GET /runs/new
  def new
    @run = Run.new
  end

  # GET /runs/1/edit
  def edit
  end

  # POST /runs
  def create
    @run = Run.new
    if @run.save
      redirect_to @run
    else
      render :new
    end
  end

  # PUT/PATH /runs/update
  def update
    choice = params.require(:choice)
    @run.current_jump.update!({choice: choice})
    if choice == @run.current_jump.correct_option
      @run.next_jump
    end
    redirect_to @run
  end

  private

  def set_run_and_jump
    @run = Run.find(params[:id])
    @jump = @run.current_jump
  end

  def set_obstacle
    @obstacle = @run.current_jump.obstacle
  end

  # def update_run_params
  #   puts 'PARAMS -----  '+ params.inspect
  #   params.require(:run).permit(:choice)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Hooprun
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = yield

app/views/runs/_form.html.haml
= form_for @run do |f|
  - if @run.errors.any?
    #error_explanation
      %h2= 'Could not start because:'
      %ul
        - @run.errors.full_messages.each do |msg|
          %li= msg
  .actions
    = f.submit "Let's go"

app/views/runs/_options.html.haml
%ul
- @obstacle.options.each do |option|
  - if @jump.choice && option != @jump.correct_option
    %li= option
  - else
    %li= button_to option, @run, method: :patch, params: {choice: option.to_s}

app/views/runs/edit.html.haml
%h1 Editing run

= render 'form'

= link_to 'Show', @run
\|
= link_to 'Back', runs_path

app/views/runs/index.html.haml
%h1 Listing runs

%table
  %thead
    %tr
      %th Jumps
      %th
      %th
      %th

  %tbody
    - @runs.each do |run|
      %tr
        %td= run.jumps
        %td= link_to 'Show', run
        %td= link_to 'Edit', edit_run_path(run)
        %td= link_to 'Destroy', run, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Run', new_run_path

app/views/runs/new.html.haml
%h1= 'Are you ready?'

= render 'form'

= link_to "Naa, I'm a chicken", '/'

app/views/runs/show.html.haml
%h1= 'You are on the run. There is an obstacle.'

%p
  = @obstacle.question
= render partial: 'options'

%p
  = link_to 'Chicken wants to go home', '/'

app/views/welcome/index.html.haml
%h1= 'Welcome'
= link_to "Let's go for a run", new_run_path